version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cart-service-postgres
    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_pass
    ports:
      - "5465:5432"
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    networks:
      - cart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cart_user -d cart_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  cart_postgres_data:

networks:
  cart-network:
    driver: bridge
